language: go
go:
  - 1.6.x

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/context
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)