language: go
go:
  - 1.6.x

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/context
script:
  - coverage run src/main_test.go

after_success:
  - bash <(curl -s https://codecov.io/bash)