language: go
go:
  - 1.6.x
go_import_path:
  - github.com/gorilla/mux
  - github.com/gorilla/context
install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/context
script:
  - go test -v ./...
